name: metpy-cookbook
channels:
  - conda-forge
dependencies:
  - cartopy
  - geopandas
  - jupyterlab
  - jupyterlab-myst
  - matplotlib
  - metpy
  - mystmd
  - numpy
  - pandas
  - scipy
  - siphon
  - xarray
